endSessionWithoutDiscovery: true

oidcEndSessionUrl: ${vauthenticator.host}/oidc/logout
auth.oidcIss: ${vauthenticator.host}
postLogoutRedirectUri: http://local.management.vauthenticator.com:8080/secure/admin/index

document:
  engine: file-system
  fs-base-path: dist

spring:
  security:
    oauth2:
      client:
        registration:
          client:
            client-id: vauthenticator-management-ui
            client-secret: secret
            client-name: VAuthenticator Management UI
            provider: vauthenticator
            scope:
              - openid
              - profile
              - email
              - admin:signup
              - admin:welcome
              - admin:email-verify
              - admin:reset-password
              - admin:change-password
              - admin:generate-password
              - admin:key-reader
              - admin:key-editor
              - admin:email-template-reader
              - admin:email-template-writer
              - mfa:enrollment
              - admin:client-app-reader
              - admin:client-app-writer
              - admin:client-app-eraser
            redirect-uri: http://local.management.vauthenticator.com:8080/login/oauth2/code/client
            authorization-grant-type: authorization_code
        provider:
          vauthenticator:
            authorization-uri: ${vauthenticator.host}/oauth2/authorize
            token-uri: ${vauthenticator.host}/oauth2/token
            user-info-uri: ${vauthenticator.host}/userinfo
            jwk-set-uri: ${vauthenticator.host}/oauth2/jwks
            user-name-attribute: email

  redis:
    database: 1
    host: localhost

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1KB

management:
  server:
    port: 8081
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

vauthenticator:
  backChannelHost: http://local.api.vauthenticator.com:9090
  session-management:
    enabled: true
    rp-iframe:
      host: http://local.management.vauthenticator.com:8080
      polling-rate: 5s
      origin: ${vauthenticator.host}
      logout-uri: /oidc_logout.html
  client:
    registrationId: client
  host: http://local.api.vauthenticator.com:9090
iamUserAwsCredentialsProvider: true