name: build vauthenticator management ui

on:
  push: { }
  workflow_dispatch: { }

jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: build testing environment
        run: |
          git clone https://github.com/VAuthenticator/spring-boot-client-starter.git
          cd spring-boot-client-starter
          mvn clean install -q

      - name: Build frontend artifacts
        run: |
          cd src/main/frontend
          npm install
          npm run-script build

      - name: Build
        run: |
          mvn install -q

      - name: docker push
        run: |
          if [[ ${GITHUB_REF##*/} == 'master' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          echo "$DOCKER_TAG"
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build . -t mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG
          docker push mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG
